

// Memory map
#define ROM_BANK_0_START_ADDR 0x0000
#define ROM_BANK_0_END_ADDR 0x4000
#define ROM_SWITCHABLE_BANK_START_ADDR 0x4000
#define ROM_SWITCHABLE_BANK_END_ADDR 0x8000
#define VRAM_START_ADDR 0x8000
#define VRAM_END_ADDR 0xA000
#define RAM_SWITCHABLE_BANK_START_ADDR 0xA000
#define RAM_SWITCHABLE_BANK_END_ADDR 0xC000
#define RAM_INTERNAL_START_ADDR 0xC000
#define RAM_INTERNAL_END_ADDR 0xE000
#define RAM_INTERNAL_ECHO_START_ADDR 0xE000
#define RAM_INTERNAL_ECHO_END_ADDR 0xFE00
#define OAM_START_ADDR 0xFE00
#define OAM_END_ADDR 0xFEA0
#define RESERVED0_START_ADDR 0xFEA0
#define RESERVED0_END_ADDR 0xFF00
#define IO_PORTS_START_ADDR 0xFF00
#define IO_PORTS_END_ADDR 0xFF4C
#define RESERVED1_START_ADDR 0xFF4C
#define RESERVED1_END_ADDR 0xFF80
#define RAM_INTERNAL_TINY_START_ADDR 0xFF80
#define RAM_INTERNAL_TINY_END_ADDR 0xFFFF
#define INTERRUPT_ENABLE_START_ADDR 0xFFFF
#define INTERRUPT_ENABLE_END_ADDR 0x10000